#Use in production when we only use pre-built image
version: '3'

services:
  web:
    image: auengauey_backend_web:latest
    container_name: web-service
    environment:
      CONNECTION_DBURL: ${DB_USER}:${DB_PASSWORD}@tcp(db:3306)/${DB_NAME}?parseTime=true
      CONNECTION_REDISURL: redis:6379
      CONNECTION_REDISSECRET: ${REDIS_SECRET}
      SECURITY_KEY_AES: ${APP_ENCRYPT_KEY}
      SECURITY_NONCE_AES: ${APP_ENCRYPT_NONCE}
      CORS_TARGET: ${WEB_CORS_TARGET}

    working_dir: /app
    ports:
      - 8100:8100
    depends_on:
      - db
      - redis
    networks:
      - backbone
    command: sh -c "go mod vendor && go run main.go"
  db:
    image: auengauey_backend_db:latest
    container_name: database-service
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/database:/var/lib/mysql
    ports:
      - 3206:3306
    networks:
      - backbone
networks:
  backbone:
    driver: bridge