name: DB CI/CD with Docker 
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Clean Go module cache
        run: go clean -modcache


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: ./web-server
          build-args: |
            "SECURITY_KEY_AES=${{secrets.APP_ENCRYPT_KEY}}"
            "SECURITY_NONCE_AES=${{secrets.APP_ENCRYPT_NONCE}}"
            "CONNECTION_DBURL=${{secrets.CONNECTION_DBURL}}"
            "CONNECTION_REDISURL=${{secrets.REDISURL}}"
            "CORS_TARGET=${{secrets.WEB_CORS_TARGET}}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-backend-web:latest

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop web-service || true
            docker rm  web-service || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-backend-web:latest
            docker run -d -p 8100:8100 \
              --name web-service \
              ${{ secrets.DOCKERHUB_USERNAME }}/auengauey-diary-backend-web:latest

